spring:
  application:
    name: sysgateway
  cloud:
    gateway:
      routes:
        - id: goods
          url: lb://goods
          predicates:
          - Path=/goods/**
          filters:
          - StripPrefix= 1
        - id: system
          url: lb://system
          predicates:
          -Path=/system/**
          filters:
          - StripPrefix=1
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true